name: container registry publish

env:
  CONTAINER_REGISTRY: docker.pg.github.com
  USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

on:
  push:
    branches: [main]
jobs:
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and Publish
        run: |
          docker build . --tag ghcr.io/eloquia/dalechang.dev:latest
          docker push ghcr.io/eloquia/dalechang.dev:latest
