name: CI

env:
  CONTAINER_REGISTRY: docker.pg.github.com
  USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: echo 'Installing npm dependencies'
      - run: npm ci
      - run: echo 'Building project'
      - run: npm run build --if-present
  #     - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Docker Registry
        run: docker login -u $USERNAME -p $ACCESS_TOKEN
      - name: Build Docker image
        run: docker build --no-cache -t $CONTAINER_REGISTRY/$REPOSITORY:latest
      - name: Push Container to Registry
        run: docker push $CONTAINER_REGISTRY/$GITHUB_REPOSITORY
