name: dalechang.me CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: echo 'Installing npm dependencies'
      - run: npm ci
      - run: echo 'Building project'
      - run: npm run build --if-present
#     - run: npm test
